version: "3.0"
services:
  elasticsearch:
    container_name: race-es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - node.name= race-es-container
      - cluster.name= docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: race-kb-container
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://race-es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:  # New Logstash service0
    container_name: race-logstash-container
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
      - ./mysql-connector-j-8.3.0.jar:/usr/share/logstash/mysql-connector-java.jar:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es-net
    depends_on:
      - elasticsearch  # Logstash depends on Elasticsearch being up


networks:
  es-net:
    driver: bridge

volumes:
  esdata:
    driver: local